### ISSUE TITLE
Issue with multiplication function

### ISSUE THREAD

**Issue by afiand** [Alexperiments/test_repo#1]
**Bug description**
The function should multiply the two numbers, but actually it performs a sum.

**Reproduction steps**
```bash
python calculator.py
```

**Expected behavior**
I expected a multiplication when multiply is called.

**Logs**

first of all you have to run the script with:

```
 python calculator.py 
```
Then, you have to choose the multiplication typing 3. Then,  you have to choose 2 numbers.   For example, selecting $num_{1}$=2 and $num_{2}$=3 I expect as output 6, whereas the output is 5.

**Comment by Alexperiments** [comment]
Hi Andrea, thanks for your suggestion!
If you want you can try to fix this bug. You just need to change the `+` in a `*`.

**Comment by afiand** [comment]
Ok thanks!
